Blocked revisions 587,615-616,618,620,631,633,641,643,645,647 via svnmerge
........
  r587 | eraxxon | 2006-08-01 19:26:47 -0500 (Tue, 01 Aug 2006) | 9 lines
  
  hpcrun: Fix (revert) pthread interception.
  
  I accidentally allowed the patch from r546 (Bart Janssen) to intercept
  pthread routines by dlopen-ing /lib/libpthread.so.0.  However, this
  will cause a problem on most OS's since /lib/tls/libpthread is now
  commonly used and subtle differences with TLS support will cause
  problems.
........
  r615 | eraxxon | 2006-08-28 09:16:40 -0500 (Mon, 28 Aug 2006) | 3 lines
  
  Partial merge with configure.ac:611 (HPCToolkit-4.2.1-optimized-code-redesign).
........
  r616 | eraxxon | 2006-08-28 09:43:03 -0500 (Mon, 28 Aug 2006) | 6 lines
  
  Resolve some compiler warnings from Intel 9.1 by full or partial
  backports of the following (from HPCToolkit-4.2.1-optimized-code-redesign):
    src/hpctoolkit/hpcrun/monitor.c 602
    src/hpctoolkit/hpcrun/monitor_preload.c 602
........
  r618 | eraxxon | 2006-08-28 14:33:51 -0500 (Mon, 28 Aug 2006) | 4 lines
  
  Fix compilation error with GCC 4.0.2 by adding a copy constructor to
  class ProfFile.
........
  r620 | eraxxon | 2006-08-28 14:59:54 -0500 (Mon, 28 Aug 2006) | 3 lines
  
  hpcprof needs libsupport to link correctly.
........
  r631 | eraxxon | 2006-09-30 13:41:13 -0500 (Sat, 30 Sep 2006) | 3 lines
  
  Convert uses of "vector<ProfFile>" to "vector<ProfFile*>" so that certain implementations of STL will not attempt attempt to use the ProfFile copy constructor and trigger its assertion.
........
  r633 | eraxxon | 2006-09-30 14:22:49 -0500 (Sat, 30 Sep 2006) | 3 lines
  
  Bump revision.
........
  r641 | eraxxon | 2006-11-09 20:03:29 -0600 (Thu, 09 Nov 2006) | 5 lines
  
  - Leaves of calling context tree are now CSProfStatementNodes (rather
    than CSProfCallsiteNotese)
  - Leaves are correctly coalesced.
........
  r643 | eraxxon | 2006-11-11 19:36:46 -0600 (Sat, 11 Nov 2006) | 2 lines
  
  Port to autoconf 2.60, automake 1.9.6, libtool 1.5.22 (use config version-ac2.60-am1.9.6-lt1.5.22).
........
  r645 | eraxxon | 2006-11-11 21:49:35 -0600 (Sat, 11 Nov 2006) | 2 lines
  
  Minor cleanup. (Performed when merging trunk r641 into HPCToolkit-4.2.1-optimized-code-redesign.)
........
  r647 | eraxxon | 2006-11-12 00:03:08 -0600 (Sun, 12 Nov 2006) | 2 lines
  
  Update.
........